"""Export apworld/gravity_circuit/data.py to client/archipelago/data.lua."""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "apworld" / "gravity_circuit"))
import data  # noqa: E402

TARGET = ROOT / "client" / "archipelago" / "data.lua"


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    lines = [
        "-- Generated by tools/gen_lua_data.py from apworld/gravity_circuit/data.py. Do not edit.",
        "local D = {}",
        f"D.GAME = {lua_str(data.GAME_NAME)}",
        "D.STAGES = {",
    ]
    for stage in data.STAGES:
        lines.append(f"  {{ key = {lua_str(stage.key)}, name = {lua_str(stage.name)}, boss = {lua_str(stage.boss)}, "
                     f"flag = {stage.clear_flag}, booster = {lua_str(stage.booster)} }},")
    lines += ["}", "D.LOCATIONS = {"]
    for loc in data.LOCATIONS:
        obj = f", obj = {lua_str(loc.obj)}" if loc.obj else ""
        lines.append(f"  {{ id = {loc.code}, kind = {lua_str(loc.kind)}, stage = {lua_str(loc.stage)}, "
                     f"index = {loc.index}, name = {lua_str(loc.name)}{obj} }},")
    lines += ["}", "D.ITEMS = {"]
    for item in data.ITEMS:
        lines.append(f"  [{item.code}] = {{ kind = {lua_str(item.kind)}, gid = {item.game_id}, "
                     f"name = {lua_str(item.name)} }},")
    lines.append("}")
    boss_stages = ", ".join(f"[{burst}] = {lua_str(stage)}" for burst, stage in sorted(data.BURST_BOSS_STAGE.items()))
    lines += [
        f"D.BURST_BOSS_STAGE = {{ {boss_stages} }}",
        "D.itemNames, D.locationNames = {}, {}",
        "for id, item in pairs(D.ITEMS) do D.itemNames[id] = item.name end",
        "for _, loc in ipairs(D.LOCATIONS) do D.locationNames[loc.id] = loc.name end",
        "return D",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    TARGET.write_text(render(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
