"""Generate apworld/gravity_circuit/money_caches.py from the game's map files.

Money caches are the big and small pickup boxes (LARGE_PICKUP_BOX / SMALL_PICKUP_BOX). Each has a stable map
object id, which the client uses to report the first time a box is broken. Only ids and section numbers are written.
"""
import math
import pathlib

from gamefiles import MAP_FILES, PLAYABLE_MAPS, load_map

TARGET = pathlib.Path(__file__).resolve().parent.parent / "apworld" / "gravity_circuit" / "money_caches.py"

# Checkpoint positions that split each stage into sections (same as the placement in data.py).
CHECKPOINT_X = {"OPTIC": [3728, 5808, 9984], "PATCH": [4576, 9776, 12576], "COOLER": [7248, 10576, 12544],
                "ELEC": [2992, 5776, 9216, 12784], "SHIFT": [5888, 14224, 21968], "BREAK": [4576, 8160, 13456]}
WAVE_CHECKPOINT_Y = [9472, 7424, 4928]
CIPHER_CHECKPOINTS = [(4272, 4000), (4176, 3232), (10688, 3248), (10176, 6832)]
CIPHER_SECTIONS = [0, 0, 1, 2]

BOX_SOURCES = (("big", "large_pickup_box"), ("small", "small_pickup_box"))


def section(stage: str, x: float, y: float) -> int:
    if stage in CHECKPOINT_X:
        return sum(1 for cx in CHECKPOINT_X[stage] if cx <= x)
    if stage == "WAVE":
        return sum(1 for cy in WAVE_CHECKPOINT_Y if cy >= y)
    if stage == "CIPHER":
        distances = [math.hypot(x - cx, y - cy) for cx, cy in CIPHER_CHECKPOINTS]
        return CIPHER_SECTIONS[distances.index(min(distances))]
    return 0


def collect():
    rows = []
    for size, source in BOX_SOURCES:
        for stage in PLAYABLE_MAPS:
            boxes = []
            for object_id, obj in load_map(MAP_FILES[stage] + ".gcl")["objects"].items():
                if obj.get("source") == source:
                    x, y = obj["spawn"]["x"], obj["spawn"]["y"]
                    progress = -y if stage == "WAVE" else x
                    boxes.append((section(stage, x, y), progress, obj.get("ID", object_id)))
            for number, (sec, _, object_id) in enumerate(sorted(boxes), 1):
                rows.append((size, stage, number, object_id, sec))
    return rows


def main() -> None:
    rows = collect()
    lines = ['"""Generated by tools/gen_money_caches.py. Do not edit.',
             "",
             "(size, stage key, cache number in the stage, map object id, checkpoint section)",
             '"""',
             "MONEY_CACHES = ["]
    lines += [f"    ({size!r}, {stage!r}, {number}, {object_id!r}, {sec}),"
              for size, stage, number, object_id, sec in rows]
    lines += ["]", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET.name}: {len(rows)} caches")


if __name__ == "__main__":
    main()
